INSERT INTO contacts (name, phone_number, email, address) VALUES ('Андрей', 7844810339, 'andrey@mail.ru', 'Владивосток, ул. Суханова, д. 25');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Ольга', 73433810340, 'olga@mail.ru', 'Ростов-на-Дону, ул. Гагарина, д. 30');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Денис', 76543810341, 'denis@mail.ru', 'Казань, ул. Университетская, д. 35');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Наталья', 72222810342, 'natalia@mail.ru', 'Самара, ул. Ленинградская, д. 40');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Павел', 74953810343, 'pavel@mail.ru', 'Владивосток, ул. Октябрьская, д. 45');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Павел', 74993810344, 'pavel1@mail.ru', 'Омск, ул. Пушкина, д. 50');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Константин', 73853810345, 'konstantin@mail.ru', 'Нижний Новгород, ул. Горького, д. 55');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Евгения', 72133810346, 'evgenia@mail.ru', 'Челябинск, ул. Кирова, д. 60');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Павел', 70343810347, 'pavel2@mail.ru', 'Владивосток, ул. Ленина, д. 65');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Анна', 79093810348, 'anna@mail.ru', 'Красноярск, ул. Мира, д. 70');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Григорий', 79093810349, 'grigoriy@mail.ru', 'Воронеж, ул. Ленинская, д. 75');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Кристина', 79093810350, 'kristina@mail.ru', 'Иркутск, ул. Карла Маркса, д. 80');
INSERT INTO contacts (name, phone_number, email, address) VALUES ('Максим', 79093810351, 'maxim@mail.ru', 'Томск, ул. Пушкина, д. 85');
INSERT INTO contacts (name, phone_number, email) VALUES ('Иван', 79093810335, 'ivan@mail.ru');
INSERT INTO contacts (name, phone_number, address) VALUES ('Мария', 79093810336, 'Екатеринбург, ул. Ленина, д. 15');
INSERT INTO contacts (name, phone_number) VALUES ('Алексей', 79093810337);
INSERT INTO contacts (name, phone_number) VALUES ('Елена', 79093810338);
INSERT INTO contacts (name, phone_number) VALUES ('Виктория', 79093810352);
INSERT INTO contacts (name, phone_number, address) VALUES ('Станислав', 79093810353, 'Белгород, ул. Гагарина, д. 95');
INSERT INTO contacts (name, phone_number, email) VALUES ('Юлия', 79093810354, 'yuliya@mail.ru');